version: '3'

services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    networks:
      - nodeapp-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
